version: '3.8'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3011:${PORT}
    depends_on:
      - db
      
  db:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5439:5432'
    volumes:
      - data:/data/db

volumes: 
 data: {}